### ISSUE TITLE
[feature request]: double quotation yaml format

### ISSUE THREAD

**Issue by yassun7010** [z3z1ma/dbt-osmosis#127]
It would be useful to be able to set the format of quotation to double quotation to be consistent with [VSCode yaml extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml), etc.

**Comment by z3z1ma** [comment]
let me take a look at ruamel settings

**Comment by z3z1ma** [comment]
Settings can now be configured via dbt project yaml

```yaml
vars:
  dbt-osmosis:
    yaml_settings:
      indent: 4
      preserve_quotes: false
```
