### ISSUE TITLE
Support create source file structure 

### ISSUE THREAD

**Issue by SabineGl** [z3z1ma/dbt-osmosis#176]
I would like to use dbt osmosis to create a source folder for each tables of a specific database schema. Since if there are a lot of tables within one schema the yaml file gets too huge. It should look like in an sql editor: if you open database folder - schema folder and within the schema folders I would like to find a folder for each table and inside the folder one source.yml for each table. 
I couldnt find any possibility based on your documentation here: [https://z3z1ma.github.io/dbt-osmosis/docs/tutorial-yaml/context]( https://z3z1ma.github.io/dbt-osmosis/docs/tutorial-yaml/context )

If you could send me a hint if and how this works this would be awesome :-) THX

I want to use it as a start recipe to get all source tables from a schema. To start building models from there. 
(if there are a possibility to use a filter pattern on table names this would be awesome too (allow []/deny [])).

**Comment by z3z1ma** [comment]
this should be possible already, I will verify

**Comment by z3z1ma** [comment]
This works :)

```yaml
name: <project_name>
config-version: 2

models:
  <project_name>:
    +dbt-osmosis: "{node.database}/{node.schema}/{node.name}.yml"
    materialized: table
    staging:
      materialized: view

seeds:
  <project_name>:
    +dbt-osmosis: "{node.database}/{node.schema}/{node.name}.yml"
```
