### ISSUE TITLE
[Feature request] Allow dbt-osmosis yaml to skip sources

### ISSUE THREAD

**Issue by FrankTub** [z3z1ma/dbt-osmosis#178]
We love dbt-osmosis and often use something like `dbt-osmosis yaml document`. We also use this as a pre-commit hook where we can exclude files that are not relevant to document. That looks something like:

```yml
- repo: https://github.com/z3z1ma/dbt-osmosis
  rev: v0.13.2
  hooks:
    - id: dbt-osmosis
      files: ^models/((?!.*sources.*).)*$
      additional_dependencies: ['dbt-core==1.8.6', 'dbt-postgres==1.8.2']
```

This does not modify our `sources.yml`. I was looking into options to skip the `sources.yml` file on the command line (without having to call pre-commit) but could not find one. We want to skip adding the columns in this file since we don't feel the need to specify a documentation for each column (specifically those that we don't use) of our source and could introduce merge conflicts etc.

What would be great if there was some sort of flag for all command line utilities under `dbt-osmosis yaml` that we could use to skip a specific file or simply skip sources.

So something like:

```shell
dbt-osmosis yaml document --skip-sources
```
