### ISSUE TITLE
Bug: BigQuery Repeated field should be ARRAY[<data_type>] in model yml

### ISSUE THREAD

**Issue by Thrasi** [z3z1ma/dbt-osmosis#181]
Given the model `testModel`:

```yml
version: 2
models:
  - name: testModel
    config:
      materialized: table
      contract:
        enforced: false
```

```sql
SELECT
  [ STRUCT( 1 AS nested_field_1,
    "a" AS nested_field_2),
  STRUCT( 2 AS nested_field_1,
    "b" AS nested_field_2),
  STRUCT( 3 AS nested_field_1,
    "c" AS nested_field_2) ] AS repeated_record,
    [1,2,3] AS repeated_int
```
```bash
dbt-osmosis yaml refactor testModel
```
produces the configuration:
```yml
version: 2
models:
  - name: testModel
    config:
      materialized: table
      contract:
        enforced: false
    columns:
      - name: repeated_record
        description: ''
        data_type: RECORD
      - name: repeated_record.nested_field_1
        description: ''
        data_type: INT64
      - name: repeated_record.nested_field_2
        description: ''
        data_type: STRING
      - name: repeated_int
        description: ''
        data_type: INT64
```
Setting `config.contract.enforced: true` and rerunning dbt
gives us a contract mismatch:
```
Column 'repeated_record' has type STRUCT<nested_field_1 INT64, nested_field_2 STRING> which cannot be coerced from query output type ARRAY<STRUCT<nested_field_1 INT64, nested_field_2 STRING>> at [9:5]
```

This does not match the BigQuery schema.  The `repeated_record` column should have `data_type: ARRAY` instead of `data_type: RECORD`
For bigquery columns we need to take into account the [mode](https://cloud.google.com/bigquery/docs/schemas#modes) of the column which can be `REQUIRED`, `NULLABLE` or `REPEATED` when specifying the `data_type` in the yml

For basic datatypes like `repeated_int`, the correct `data_type` there is `data_type: ARRAY<INT64>`
