### ISSUE TITLE
[Feature] Support more complex configuration on a per node basis

### ISSUE THREAD

**Issue by z3z1ma** [z3z1ma/dbt-osmosis#191]
Instead of (or in addition to) CLI flags, we should control certain attributes using the hierarchical config which gives fine grained control in dbt project yml

```yaml
models:
  "<YOUR_PROJECT_NAME>":
    +dbt-osmosis-options:
      numeric-precision-and-scale: true
      string-length: true
```

Or in sql

```jinja
{{ config(..., dbt_osmosis_string_length=true) }}
```

Now that the codebase is refactored, its extremely easy to see how we might do this and even have a helper method that checks 3 or 4 places by default with some precedence.

**Comment by z3z1ma** [comment]
Further defining specification and approach. This may well supersede the cli flags, maybe. Its much more deterministic, granular, and codified approach.

```yaml
    models:
        project:
            staging:
                +dbt-osmosis: path/spec.yml
                +dbt-osmosis-options:
                    char-length: true
                    numeric-precision: true
                    skip-add-columns: true
                +dbt-osmosis-skip-add-tags: true


    models:
      - name: foo
        meta:
            char-length: false
        columns:
          - bar:
            meta:
                dbt-osmosis-skip-meta-merge: true # per-column options
                dbt-osmosis-options:
                    output-to-lower: true

    So we check for
    From node column meta
    - dbt-osmosis-<key>
    - dbt-osmosis-options.<key>
    From node meta
    - dbt-osmosis-<key>
    - dbt-osmosis-options.<key>
    From node config
    - dbt-osmosis-<key>
    - dbt-osmosis-options.<key>
    - dbt_osmosis_<key> # allows use in {{ config(...) }} by being a valid python identifier
    - dbt_osmosis_options.<key> # allows use in {{ config(...) }} by being a valid python identifier
```
