### ISSUE TITLE
Update changelog and documentation page, add migration guide for 1.x.x

### ISSUE THREAD

**Issue by z3z1ma** [z3z1ma/dbt-osmosis#192]
We need to layout the breaking changes between 1.x.x and <=0.13/0.14 very clearly. 

There are not many but some are important and notable. 

Off top, in 1.1.1 -- I changed the structure of `vars.dbt-osmosis` so we werent stuffing separating things in one dict

New structure is as follows, so users will need to nest sources one more key down.

```yaml
vars:
  dbt-osmosis:
    sources:
      <old source settings>
    column_ignore_patterns:
      <global regex patterns of columns not to inject or document>
    yaml_settings:
      <kwargs applied directly to ruamel.yaml object>
```

Another is that I renamed 3 cli flags. 
`--char-length` -> `--string-length`
`--numeric-precision` -> `--numeric-precision-and-scale`
`--catalog-file` -> `--catalog-path`

One more is that `organize`/`refactor` both can take an `--auto-apply` flag. Without that flag, they will prompt `[y/N]` t confirm if there are files to shuffle and you can review it first. To have no prompt behavior for uses such as in CI, the flag should be passed.

`seeds:` in dbt_project.yml should also have a `+dbt-osmosis: <path>` now or users will get an exception. This is new in 1.x.x

We can configure stuff in a lot of ways now. 

```yaml
models: # dbt_project.yml
  jaffle_shop_duckdb:
    # this works by the way for specify yaml paths which have the same taxonomy as the database, pretty cool
    +dbt-osmosis: "{node.database}/{node.schema}/{node.name}.yml"
    # applies to all models in the project as per usual
    +dbt-osmosis-options:
      skip-merge-meta: true
    materialized: table
    staging:
      # applies to only the staging folder
      +dbt-osmosis-options:
        numeric-precision-and-scale: false
        output-to-lower: true
        skip-merge-meta: false # takes precedence
      materialized: view
```

```sql
{{ config(materialized="view", dbt_osmosis_options={"prefix": "account_"}) }}

select
  id as account_id, -- this will inherit meta/tags/docs from `id` correctly despite its output being `account_id` thanks to the `prefix` opt
  name as account_name,
  age as account_age_in_days
from accounts
```

```yaml
models: # schema.yml
  - name: foo
    meta:
      string-length: false
      prefix: user_ # we strip this prefix to inherit from columns upstream, useful in staging models that prefix everything
    columns:
      - bar:
        meta:
          dbt-osmosis-skip-meta-merge: true # per-column options as a flat key
          dbt-osmosis-options:
            output-to-lower: true # per-column options under an options key

```

A non breaking, but important behavioral change is that children documentation will no longer override existing documentation for  node by default. I actually think that goes against the idea of the tool. From now on, `--force-inherit-descriptions` will basically give you the legacy behavior. But the purpose of the tool is mostly that you can updates docs downstream and they are semantically meaningful changes, hence you opt-in to overrides. Much better. This mean `osmosis_keep_description` is deprecated (a no-op)

On the same note as above, child meta keys will not override the target nodes. Rather the target nodes meta is merged into upstream cumulative dict. Also much better. Overall it makes the tool less finicky and overwrite-y.

I won't even get into how many lines of code we changed with the refactor, but I consider it a massive improvement to readability and extensibility. Its ridiculously easy now comparatively speaking to hack in some more options. 

To that end, I added a plugin system with `pluggy` so users can supply custom fuzzing logic to provide a list of candidate column names for a given input name. I used this plugin system to implement our basic 'fuzz' things (camel case, pascal, prefix, upper). We need to document this too. 

Lastly, we should add more end to end tests with stabilization of the package. And maybe try the LLM thing again.

PS. we may yank the pypi release for 1.0.0 just so everyone has 1.1.x and higher moving forward since I made a decent breaking change there (renamed cli flags) added new config resolution approach.
