### ISSUE TITLE
Error caused by seeds

### ISSUE THREAD

**Issue by karim-soufi** [z3z1ma/dbt-osmosis#193]
Hello,

Trying to use dbt-osmosis. I have the following error for my seeds.
I tryed setting seeds in properties file or dbt_project, same outcome.

dbt_osmosis.core.osmosis.MissingOsmosisConfig: Config key `dbt-osmosis: <path>` not set for model ....

dbt-core: 1.8.8 (dbt-osmosis not compatible with 1.9.0 because of streamlit version)
dbt-redshift: 1.9.0
dbt-osmosis: 1.1.5

best regards

**Comment by z3z1ma** [comment]
@karim-soufi 

```yaml
# in dbt_project.yml
name: ...
models: ...

# seeds is its own top level key, set your config there
seeds:
  +dbt-osmosis: schema.yml
```
