### ISSUE TITLE
Bug: Upgrading to latest dbt-osmosis 1.1.17 generates yaml output that does not render properly by dbt docs serve

### ISSUE THREAD

**Issue by FrankTub** [z3z1ma/dbt-osmosis#195]
I bumped dbt-osmosis from 0.13.2 to 1.1.17 and run 

```bash
dbt-osmosis yaml document
```
This creates some yaml files that dbt docs is ignoring the `description` keys where the description is split improperly to multiple lines.

So in the `0.13.2` version my yaml would look like:

```yaml
      - name: sales_invoice_item_item_type
        description: Type of the sales invoice item, this is a classification that is used to display in the Beehive UI
        data_type: character varying
```

When I try it out in `1.1.17` the output would be like:

```yaml
...
      - name: sales_invoice_item_item_type
        description: Type of the sales invoice item, this is a classification that is used to display
          in the Beehive UI
        data_type: character varying
...
```

Now when I run:

```bash
dbt docs generate
dbt docs serve
```
All my descriptions are empty for all columns and for the model itself. This is probably due to improper format of the yaml file? Is there a way to prevent this from happening?
