### ISSUE TITLE
Bigquery record nested fields no longer generated

### ISSUE THREAD

**Issue by cwmuller** [z3z1ma/dbt-osmosis#202]
There has been a change to how record data types are documented. Up until the latest major release, each nested field was correctly added.

The following model:

```
select struct(1 as , "a" as nested_field_2) as nested_field
```

dbt-osmosis version 0.13.2 (dbt 1.8.9 and dbt-bigquery 1.8.3) outputs this:

```
version: 2
models:
  - name: example
    columns:
      - name: nested_field
        data_type: RECORD
      - name: nested_field.nested_field_1
        description: ''
        data_type: INT64
      - name: nested_field.nested_field_2
        description: ''
        data_type: STRING
```

dbt-osmosis version 1.1.19  (dbt 11.9.1 and dbt-bigquery 1.9.1) outputs this:

```
version: 2
models:
  - name: example
    columns:
      - name: nested_field
        data_type: RECORD
```
