### ISSUE TITLE
[bug] Passing preserve_quotes to dbt-osmosis seems to do nothing

### ISSUE THREAD

**Issue by wahlrkr** [z3z1ma/dbt-osmosis#203]
Hi

requested feature of preserving quotes was acknowledged here https://github.com/z3z1ma/dbt-osmosis/issues/127 but currently it seems, that the config flag of `preserve_quotes` does nothing. I tried it with both `false` and `true` but running `dbt-osmosis yaml refactor` still gives exactly the same results i.e. still cleans up the quotes automatically.

**Version**

1.1.9

**dbt-osmosis config**

```
vars:
  dbt-osmosis:
    yaml_settings:
      indent: 2
      explicit_start: true
      preserve_quotes: true
```

**Original**

```
version: 2

models:
  - name: social_media_v1__fbpage_page_daily
    latest_version: 1
    versions:
      - v: 1
    columns:
      - name: platform
        description: 'Hard coded source'
        data_type: varchar
```

**How it is**

```
---
version: 2

models:
  - name: social_media_v1__fbpage_page_daily
    latest_version: 1
    versions:
      - v: 1
    columns:
      - name: platform
        description: Hard coded source
        data_type: varchar
```

**How it should be**

Like the "original" without no quotation changes.

Thanks 🙂

**Comment by z3z1ma** [comment]
Its working for me using this as an example. These are all set directly on the ruamel YAML round trip serializer instance. I tested modifying the `preserve_quotes` abck and forth and it worked as expected so having trouble reproducing. 

```yaml
vars:
  dbt-osmosis:
    yaml_settings:
      map_indent: 2
      sequence_indent: 4
      brace_single_entry_mapping_in_flow_sequence: true
      explicit_start: true
      preserve_quotes: true
```

**Comment by wahlrkr** [comment]
Hmm ok 🤔 I read that `ruamel.yaml` can be sometimes tricky with its auto-quotations and old vs. new API especially with the `roundTripLoader/Dumper`

(https://stackoverflow.com/questions/76038205/ruamel-yaml-some-comments-get-lost-in-round-trip-dump)
(https://stackoverflow.com/questions/74013838/how-to-avoid-ruamel-yaml-round-trip-dump-from-printing-in-between-yaml-key)

So my only suspect would be that something happens here https://github.com/z3z1ma/dbt-osmosis/blob/5f48d6ce06ea0729577b1f4405a0759bfc9cec3b/src/dbt_osmosis/core/osmosis.py#L370-L378 during some corner case.

I try to get another example. If it helps, we use combo of `snowflake + dbt + dbt-osmosis`.

**Comment by aibazhang** [comment]
Same issue here.

`dbt-osmosis==1.1.17`

When I run `dbt-osmosis yaml refactor` with

```
    yaml_settings:
      map_indent: 2
      sequence_indent: 4
      brace_single_entry_mapping_in_flow_sequence: true
      preserve_quotes: true
```

The quotes for `models[].description` stay, but quotes for `models[].columns[].description` were cleaned up.

> So my only suspect would be that something happens here

However, I tested `ruamel.yaml` (only load and dump a model yaml file) with the same config as function `str_representer`, the quotes for both `models[].description` and `models[].columns[].description` weren't cleaned up.

I checked the source code, I cannot find any difference in the handling `models[].description` and `models[].columns[].description`
https://github.com/z3z1ma/dbt-osmosis/blob/5f48d6ce06ea0729577b1f4405a0759bfc9cec3b/src/dbt_osmosis/core/osmosis.py#L1427-L1484
