### ISSUE TITLE
Only single column generated per model (Bigquery adapter)

### ISSUE THREAD

**Issue by cwmuller** [z3z1ma/dbt-osmosis#206]
Running any model under dbt 1.9.2, dbt-bigquery 1.9.1, and dbt-osmosis 1.1.11, returns schemas with only a single column, whilst producing the following warning:

```
Could not introspect columns for CatalogKey(database=(...), schema=(...), name='testmodel'): maximum recursion depth exceeded
```

For example, this model:

```
select "a" as foo, "b" as bar
```

Generates the following schema:
```
version: 2
models:
  - name: testmodel
    columns:
      - name: foo
        data_type: STRING
```
