### ISSUE TITLE
(Bigquery adapter) Originating records dropped from schema during unnesting

### ISSUE THREAD

**Issue by cwmuller** [z3z1ma/dbt-osmosis#207]
So, the latest version 1.1.12 indeed solved the issue of nested fields not being generated. However, the behaviour is now such that fields within records are unnested, whilst the originating record column is dropped from the schema. Up until the the previous major version, 0.14.0, both the record object and the nested fields were added to the schema, so the output of 1.1.12 is not at parity with 0.14.0.

Using the following model as example:
```
select struct(1 as nested_field_1 , "a" as nested_field_2) as nested_field
```

The resulting schema is:
```
version: 2
models:
  - name: example
    columns:
      - name: nested_field.nested_field_1
        description: ''
        data_type: INT64
      - name: nested_field.nested_field_2
        description: ''
        data_type: STRING
```

The expected output (<=0.14.0) is:
```
version: 2
models:
  - name: example
    columns:
      - name: nested_field
        data_type: RECORD
      - name: nested_field.nested_field_1
        description: ''
        data_type: INT64
      - name: nested_field.nested_field_2
        description: ''
        data_type: STRING
```

I suppose including the originating record in the schema when the objects within are being documented could seem a little unnecessary, but for our purposes, we use the record objects in the schemas in downstream processes, and would really like this behaviour to return.
