### ISSUE TITLE
dbt-osmosis v1: Extra Fields Added to constraints in YAML File

### ISSUE THREAD

**Issue by syou6162** [z3z1ma/dbt-osmosis#212]
Thanks to https://github.com/z3z1ma/dbt-osmosis/pull/204, I was able to update to dbt-osmosis v1. Thank you 👍 .

When I upgraded to v1, I noticed that extra elements were being added to the yaml file in cases where I was using `constraints`.

I'm assuming that the yaml file before running osmosis is as follows.

```yaml
version: 2
models:
  - name: my_model
    config:
      contract:
        enforced: true
    columns:
      - name: item_id
        data_type: STRING
        constraints:
          - type: not_null
```

When running osmosis with the v1 series, extra elements are added to `constraints` as follows.

```yaml
version: 2
models:
  - name: my_model
    config:
      contract:
        enforced: true
    columns:
      - name: item_id
        description: my description
        data_type: STRING
        constraints:
          - type: not_null
            name:
            expression:
            warn_unenforced: true
            warn_unsupported: true
            to:
            to_columns: []
```

It may seem harmless to add extra elements to yaml, but for example, `to_columns` is an option for `foreign_key`, so it shouldn't appear in the above `not_null`. I think that extra elements should not be added because it can cause confusion among developers in the team.

- https://docs.getdbt.com/reference/resource-properties/constraints#defining-constraints

I think that `constraints` is included in `ColumnInfo` and that extra fields are added when `from_dict` is executed.

- https://github.com/dbt-labs/dbt-core/blob/c0423707b07237a81f910a9cd35a9de41695f294/core/dbt/artifacts/resources/v1/components.py#L59-L71
- https://github.com/z3z1ma/dbt-osmosis/blob/5f48d6ce06ea0729577b1f4405a0759bfc9cec3b/src/dbt_osmosis/core/osmosis.py#L2077

I don't know if it's easy to fix, but if it seems like it could be fixed, I was thinking of sending a pull request.
