### ISSUE TITLE
If the description is empty, the field itself will disappear when I run `dbt-osmosis yaml refactor`

### ISSUE THREAD

**Issue by syou6162** [z3z1ma/dbt-osmosis#214]
If the description is an empty string, running `dbt-osmosis yaml refactor` will cause the description field itself to disappear.

For example, if you run `dbt-osmosis yaml refactor` on the following yaml, 

```yaml
version: 2
models:
  - name: my_model
    columns:
      - name: example_column
        description: ""
        data_type: STRING
```

it will become

```yaml
version: 2
models:
  - name: my_model
    columns:
      - name: example_column
        data_type: STRING
```

It is possible to add the description field manually, but if a human adds the description field each time, the following problems will occur.

- The order in which the description properties are added will differ depending on the person
  - If you are running dbt-osmosis in CI/CD, the order of the description properties may change, making it difficult to understand the differences
  - If dbt-osmosis retains the description properties with empty characters, this problem will be less likely to occur

Prior to dbt-osmosis v1, even if the description was empty, the field itself was retained, so I think it would be good to have an option to reproduce that behavior.
