### ISSUE TITLE
New tables not added to sources when yaml file for that source already exists

### ISSUE THREAD

**Issue by w0ut0** [z3z1ma/dbt-osmosis#217]
Hi!

We seed a couple of schemes in dbt_project.yml, like

```
(...)
vars:
  dbt-osmosis:
    sources:
      mysource_a:
        database: "mart"
        path: "mart/mysource_a.yml"
      mysource_b:
        database: "mart"
        path: "mart/mysource_b.yml"
```
When we run `dbt-osmosis yaml refactor` the first time, this works as expected. All tables from the schema are discovered, and of those tables the columns etc. are fetched. We commit the 2 generated files.

However, when a new table is added in the schema, this is never added. 
New columns/changes in the tables that where picked up the first time are updated as expected.

I propose that, when a source is available in `vars.dbt-osmosis.sources`, that `adapter.list_relations` is called for every source schema in the vars, and if new tables are discovered, these are merged into the yaml file.
