### ISSUE TITLE
Combination of --force-inherit-descriptions and --use-unrendered-descriptions not working as expected

### ISSUE THREAD

**Issue by larssnek** [z3z1ma/dbt-osmosis#219]
I've seen some behavior that I was not expecting. Please let me know if the following is actually the expected behavior.

When I run `dbt-osmosis yaml document my_model --force-inherit-descriptions --use-unrendered-descriptions` for columns with existing descriptions having doc() reference where dbt-osmosis doesn't find an upstream column it will render the description.

E.g.
```yml
-- my_model.yml

version: 2
models:
  - name: my_model
    columns:
      - name: my_column
        description: '{{ doc("my_description") }} Source: my_source_column.
```
Where `{% docs my_description %} my dummy description. {% enddocs %}` and dbt-osmosis is not able to detect the upstream column. After running `dbt-osmosis yaml document my_model --force-inherit-descriptions --use-unrendered-descriptions` my yml-file looks like this:

```yml
-- my_model.yml

version: 2
models:
  - name: my_model
    columns:
      - name: my_column
        description: 'my dummy description. Source: my_source_column.'
```

To verify dbt-osmosis didn't detect some upstream description I removed the description from my yml file altogether and ran the command again and nothing was changed.

Versions:
dbt-osmosis, version 1.1.13
dbt-core, version 1.9.2
dbt-databricks, version 1.9.5

By the way this also seems similar to what was reported in [this issue](https://github.com/z3z1ma/dbt-osmosis/issues/197), but since it was lacking some details I am not 100% sure it was the same thing.
