### ISSUE TITLE
Request: `yaml refactor` | Custom naming for staging models .yml file

### ISSUE THREAD

**Issue by jim256** [z3z1ma/dbt-osmosis#233]
First, I want to say how much I love this project. It is so useful (honestly, I don't see how someone would manage a dbt-core project well without it). And additionally, performance is ⚡. I use this in tandem with dbt-coves, and I'm constantly wishing that coves paid the attention to performance that you do 🙏

Is there a way to make the output filename of `yaml refactor` use the name of the source?

For example, let's say I have the following source file:

```
version: 2

sources:
  - name: sales_db__customer_schema
    database: sales_db
    schema: customer_schema
    tables:
      - name: first_order_dates
        description: ''
        columns:
          - name: VALUE
            data_type: VARIANT
          - name: ...
```

This source file lives in `models/staging/sales_db/customer_schema`.

I'd like to be make my filename be `sales_db__customer_schema__models.yml`. Is that currently possible?

I tried using `{parent}`, but that uses (in this example) `customer_schema.yml`.

**Comment by jim256** [comment]
I tried this using `node`, as suggested [here](https://z3z1ma.github.io/dbt-osmosis/docs/tutorial-yaml/context#node), but I couldn't get it to work.
On this note, I think a doc change may be needed there. The sample:
`+dbt-osmosis: "node.fqn[-2]/{node.resource_type}_{node.language}/{node.name}.yml"` inserts the string literal `node.fqn[-2]` into the folder name.

I tried a few variations, but couldn't crack it. Adding braces -> `{node.fqn[-2]}` results in:
```
  File "/Users/<user name redacted>/.local/share/uv/tools/dbt-osmosis/lib/python3.12/site-packages/dbt_osmosis/core/osmosis.py", line 1130, in get_target_yaml_path
    rendered = tpl.format(node=node, model=node.name, parent=node.fqn[-2])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

**Comment by jim256** [comment]
Awesome, thank you so much @z3z1ma!

**Comment by jim256** [comment]
@z3z1ma, a follow-up question here:
I have:
```
vars:
  dbt-osmosis:
    sources:
      aa_mart__aa_analytics:
        path: "staging/aa_mart/_{node.source_name}__sources.yml"
        database: "aa_mart_qa"
        schema: "aa_analytics"
```

If I execute
```
dbt-osmosis yaml refactor --force-inherit-descriptions --use-unrendered-descriptions --skip-add-data-types --auto-apply --output-to-lower --project-dir dbt  --fqn staging.aa_mart.aa_analytics
```

Then the resulting file name is literally: "_{node.source_name}__sources.yml". Am I using this how you were intending? Is this what you'd expect?
