### ISSUE TITLE
Don't render {{ var }}'s in policy tags when running document or refactor

### ISSUE THREAD

**Issue by paulbakkerbloom** [z3z1ma/dbt-osmosis#266]
First of all, thanks for writing the package :D

When running `document` or `refactor` command, the {{ vars }} that are listed under `policy_tags` get rendered. I don't want that to happen, since the value of these tags changes with the environment / target they run in. It would be nice to add a flag for this.

My model yaml looks like this

```
version: 2
models:
  - name: foo
    description: bar
    columns:
      - name: user_id
        description: 'foobar'
        policy_tags:
          - '{{ var("policy_tag_user_id") }}'
```

But after running dbt-osmosis look like this:

```
version: 2
models:
  - name: foo
    description: bar
    columns:
      - name: user_id
        description: 'updated foobar'
        policy_tags:
          - >-
            projects/some_project/locations/europe-west4/taxonomies/number/policyTags/number
```

**Comment by z3z1ma** [comment]
Thank you for reporting this issue! This is now fixed in the latest version of dbt-osmosis.

## Summary of Changes

**New Feature:** `--prefer-yaml-values` flag
A new CLI flag `--prefer-yaml-values` has been added that prioritizes YAML values as-is for ALL fields, preserving unrendered jinja templates like:
- `{{ var('policy_tag_user_id') }}`
- `{{ env_var('MY_ENV_VAR') }}`
- `{{ doc('block_name') }}`
- Any other jinja templates

**Expanded Jinja Detection:**
The `PropertyAccessor._has_unrendered_jinja()` method now detects all common jinja patterns:
- `{{ doc() }}` - Doc blocks
- `{{ var() }}` - Variable substitution  
- `{{ env_var() }}` - Environment variables
- `{{ }}` - Generic jinja expressions
- `{% %}` - Generic jinja statements
- Support for nested lists (e.g., `policy_tags`) and dicts (e.g., `meta`)

**Backward Compatibility:**
The existing `--add-inheritance-for-specified-keys=policy_tags` flag continues to work for granular control over specific fields.

## Usage Examples

```bash
# New ergonomic way - preserves ALL unrendered jinja templates
dbt-osmosis yaml document --project-dir . --profiles-dir . --prefer-yaml-values

# Existing granular way - preserves only specified keys
dbt-osmosis yaml document --project-dir . --profiles-dir . --add-inheritance-for-specified-keys=policy_tags
```

## Your Example Use Case

```yaml
# Before (your issue):
# After running dbt-osmosis, {{ var(...) }} was replaced with rendered value
policy_tags:
  - projects/some_project/locations/europe-west4/...

# After (with --prefer-yaml-values):
# The unrendered template is preserved
policy_tags:
  - '{{ var("policy_tag_user_id") }}'
```

Thank you again for the detailed issue report!
