### ISSUE TITLE
Bug: Extra linebreak before injected column and missing linebreak after

### ISSUE THREAD

**Issue by jaredx435k2d0** [z3z1ma/dbt-osmosis#40]
If I run dbt-osmosis yaml refactor on an existing source, and a column has been added to a table since the last time I ran it, it's added like this:

```
version: 2

sources:
  - name: my_source_name
    description: ""
    database: my_db_name
    schema: public
    tables:
      - name: my_table
        description: ""
        columns:
          - name: date
            description: ""

          - name: new_column_inserted_by_dbt_osmosis
      - name: my_next_table
```

Additional context
python 3.9.16
macOS 13.2 (22D49)
Snowflake 7.3.1
dbt-core==1.3.2
dbt-extractor==0.4.1
dbt-osmosis==0.9.8
dbt-snowflake==1.3.0

**Comment by jaredx435k2d0** [comment]
Similarly, when removing an extra column from a yml file, the empty line separating tables will be removed:

Before:
```
models:
  - name: first_table
    description: ""
    columns:
      - name: id
      - name: extra_column_to_remove
  
  - name: second_table
    description: ""
    columns:
      - name: id
      - name: other_column
```

After:
```
models:
  - name: first_table
    description: ""
    columns:
      - name: id
  - name: second_table
    description: ""
    columns:
      - name: id
      - name: other_column
```
