### ISSUE TITLE
Add metadata to connect source models to "staging" models to enable more robust inheritance

### ISSUE THREAD

**Issue by jaredx435k2d0** [z3z1ma/dbt-osmosis#52]
Given the following, when I run `yaml refactor`, the description from the source table `addresses` doesn't bubble up to the stg_some_schema__addresses staging model _stg_some_schema.yml (even though the description from the `ID` field does):

_this_db__some_schema__sources.yml:
```
version: 2

sources:
  - name: this_db__some_schema__source
    database: this_db
    schema: some_schema
    tables:
      - name: addresses
        description: 'this table has addresses'
        columns:
          - name: ID
            description: 'this is the ID'
```

_stg_some_schema.yml:
```
version: 2

models:
  - name: stg_some_source__addresses
    columns:
      - name: ID
        description: this is the ID
```

stg_some_schema__addresses.sql:
```
SELECT
	ID
,	NAME
,	ADDRESS_LINE1
,	ADDRESS_LINE2
,	CITY
,	DISTRICT_OR_COUNTY
,	STATE_CODE
,	COUNTRY_CODE
,	POSTAL_CODE
,	CREATED_AT
,	UPDATED_AT
,	_FIVETRAN_SYNCED

FROM
	{{ source("this_db__some_schema__source", "addresses") }}
```

I'm doing one .yml file per source, and one .yml file per corresponding staging schema

Python 3.10.10
dbt-core==1.4.5
dbt-extractor==0.4.1
dbt-osmosis==0.11.14
dbt-snowflake==1.4.2
