### ISSUE TITLE
Support the `--profile` and `--vars` options

### ISSUE THREAD

**Issue by yu-iskw** [z3z1ma/dbt-osmosis#59]
## Motivation
I would like to specify a dbt profile by `--profile` and dbt variables by `--vars`.

First, we have multiple profiles and select one based on the running environment. So, our default profile is set with a local development one. We would like to pass a profile to the CLI.

Second, our dbt models requires variables set by the `--vars` option so that we dynamically switch the Google Cloud project. We have different YAML files corresponding the destination environments respectively. We run a dbt command like `dbt build --vars "$(cat vars-production.yml)"`. So, we would like to pass dbt variables to dbt-osmosis too.

```yaml
# vars-production.yml
projects:
  project-a: "project-a-production"

# vars-staging.yml
projects:
  project-a: "project-a-staging"
```

This is a pseudocode to dynamically get the destination Google Cloud project ID
```sql
{% set gcp_project = var('projects')['project-a'] %}

{{
  config(
    materialized="table",
    database=gcp_project,
    schema="dwh_ai_inquiry",
    alias="answer",
  )
}}

SELECT ...
```
