### ISSUE TITLE
Table description not populating downstream

### ISSUE THREAD

**Issue by jaredx435k2d0** [z3z1ma/dbt-osmosis#65]
I have the following files:

_schema_name__sources.yml:
```
version: 2

sources:
  - name: [my_source_name_redacted]
    database: [my_db_name_redacted]
    schema: [my_schema_name_redacted]
    tables:
      - name: current_fbm_inventories
        description: 'Stay away from this table, use current_inventories instead'
        columns:
          - name: PRODUCT_ID
          - name: FBM_QUANTITY
```

_stg_source_name.yml:
```
version: 2

models:

  - name: stg_[source_name]__current_fbm_inventories
    description: ""
    columns:
      - name: PRODUCT_ID
      - name: FBM_QUANTITY
```

stg_[source_name]__current_fbm_inventories.sql:
```
SELECT
	PRODUCT_ID
,	FBM_QUANTITY

FROM
	{{ source("source_name", "current_fbm_inventories") }}
```

The description in _schema_name__sources.yml doesn't appear in _stg_source_name.yml when I run `dbt-osmosis yaml refactor`.

It should, right?

dbt-core==1.4.6
dbt-extractor==0.4.1
dbt-osmosis==0.11.17
dbt-snowflake==1.4.2

Python 3.10.10
