### ISSUE TITLE
Use identifier when available in yaml config to find relation in database

### ISSUE THREAD

**Issue by Lawiss** [z3z1ma/dbt-osmosis#73]
Hello,

I have errors when running `yaml refactor` and relations have different name in database than the one in the yaml source/model config. Example of a source yaml config with an identifier :
```
version: 2
models: []
sources:
  - name: raw_zone_gsheet
    description: Tables qui proviennent de Google Sheet.
    tables:
      - name: collectivites
        identifier: coordonnees-epci-fp-2022-last
```
dbt-osmosis says `Relation td-datawarehouse.raw_zone_gsheet.collectivites does not exist in target database, cannot resolve columns` as it uses the value from the "name" key instead of the value from the "identifier" key.
Is it possible to use the `identifier` if it is configured?
