### ISSUE TITLE
Support inheriting doc-blocks in description

### ISSUE THREAD

**Issue by dsjoho** [z3z1ma/dbt-osmosis#8]
Hi, thanks for writing this tool - it looks like just what I want :)

I found a possible improvement: when a description contains a doc-block, it would be nice if the inherited downstream descriptions re-used the reference instead of injecting the contents of the doc block.

Example:
```
models:
- name: first
  columns:
  - column_a: '{{ doc("column_a_description") }}'
```
will in a child_model named `second` be rendered into
```
models:
- name: second
  columns:
  - column_a: This text is available in the column_a_description.md file.\r\n\r\nWith a newline
```

If the reference is kept constant it will be very clear that the place to edit the description is someplace else.
Also, the current injection inserts a lot of newlines which makes the rendered yml ugly. Including the reference instead of the contents would solve both of these nuisances.
