### ISSUE TITLE
[Feature Request] Ignore specific source columns

### ISSUE THREAD

**Issue by AaronCoquet-Easypark** [z3z1ma/dbt-osmosis#88]
I have a project that uses Fivetran (and some other tools) to sync data to Snowflake as sources for dbt. I don't want to include certain columns (`_FIVETRAN_SYNCED`, for example), since they're not terribly useful for our use case.
I'd like to be able to configure dbt-osmosis to not inject them for every single source.

**Comment by z3z1ma** [comment]
Added in latest release `0.12.1`

You can leverage this via adding a `_blacklist` key to your `dbt-osmosis` vars config as so:


```yaml
# dbt_project.yml


vars:
  dbt-osmosis:
    _blacklist: ["columns", "to", "exclude", "[Rr]egex.*is_ok"] # <- this is the new reserved key
    <source_name>: <path>
    <source_name>:
      path: <path>
      schema: <schema>
```
